TRUNCATE TABLE "Invoices" RESTART IDENTITY;
TRUNCATE TABLE "ProductSupplier" RESTART IDENTITY;
TRUNCATE TABLE "Products" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Suppliers" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Categories" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Customers" RESTART IDENTITY CASCADE;